# We simply inherit the Python 3 image. This image does
# not particularly care what OS runs underneath
FROM python:3.6
# Install system dependencies
RUN apt-get update && apt-get install -y libfontconfig
# Set an environment variable with the directory
# where we'll be running the app
ENV APP /app
# Create the directory and instruct Docker to operate
# from there from now on
RUN mkdir $APP
WORKDIR $APP
# Copy the requirements file in order to install
# Python dependencies
COPY requirements.txt .
# Install Python dependencies
RUN pip install -r requirements.txt
# Copy nltk installer file
COPY install_nltk_deps.py .
# Install nlp dependencies
RUN python install_nltk_deps.py
# We copy the rest of the codebase into the image
COPY . .
# Set permissions for phantomjs binary
RUN chmod +x phantomjs-2.1.1-linux-x86_64/bin/phantomjs
